name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: your-image-name:latest
        outputs: type=docker,dest=docker-image.tar

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: docker-image.tar
